#!/bin/bash 

XMLSTARLET=$(which xmlstarlet) 
ED_CMD="ed --inplace -P"
SERVER_CONFIG="/opt/tomcat/conf/server.xml"
REDEPLOY_CONF="/etc/jelastic/redeploy.conf"
CURRENT_NODE_INTERNAL_IP=$(ip a | grep -A1 venet0 | grep inet | awk '{print $2}'| sed 's/\/[0-9]*//g' | tail -n 1)
CLUSTER_XPATH="Server/Service/Engine/Cluster"
[ -f /etc/jelastic/metainf.conf ] && . /etc/jelastic/metainf.conf 

NEW_MANIFEST="true";

if [ "x$COMPUTE_TYPE" != "xtomee" -a $COMPUTE_TYPE_VERSION -le 8 ] ; then
    NEW_MANIFEST="false";
fi

addVersionSpecificConfig(){
    if [ "$NEW_MANIFEST" == "true" ]; then
        sed -i "/<\/Channel>/e curl ${1}/conf/cluster-tomcat-9-10-tomee.xml" ${SERVER_CONFIG};
    else
        sed -i "/<\/Channel>/e curl ${1}/conf/cluster-tomcat-7-8.tpl" ${SERVER_CONFIG};
    fi
}

applyClusterTemplate(){
    if [ $# -eq 0 ]
    then
        echo "No arguments supplied";
	return 1;
    fi
    xmlstarlet sel -Q -t -v "Server/Service/Engine/Cluster" ${SERVER_CONFIG} || { sed -i "/<\/Engine>/e curl ${1}/conf/cluster-general.tpl" ${SERVER_CONFIG}; addVersionSpecificConfig ${1}; }
}

removeNode(){
    if [ $# -eq 0 ]
    then
        echo "No arguments supplied";
        return 1;
    fi
    if [ "$NEW_MANIFEST" == "false" ]; then
        [[ "x${CURRENT_NODE_INTERNAL_IP}" == "x${1}" ]] && return 0;
    fi
    sed -i "/Member.*host=\"${1}\"/d" ${SERVER_CONFIG};
}

addNode(){
    if [ $# -lt 2 ]
    then
        echo "No arguments supplied";
        return 1;
    fi
    read A B C D <<<"${1//./ }"
    MEMBER_ID="$(echo $A|tail -c 3),$(echo $B|tail -c 3),$(echo $C|tail -c 3),$(echo $D|tail -c 3),$(echo $2|tail -c 3)"
    if [ "$NEW_MANIFEST" == "true" ]; then
        if ! grep -q "Member.*host=\"${1}\"" ${SERVER_CONFIG}; then 
            if [[ "x${CURRENT_NODE_INTERNAL_IP}" == "x${1}" ]]; then
		sed -i "/LocalMember[[:space:]]*className/d" ${SERVER_CONFIG}
                sed -i "/<\/Membership>/i \<LocalMember className=\"org.apache.catalina.tribes.membership.StaticMember\" uniqueId=\"{0,1,2,3,4,5,6,7,8,9,10,$MEMBER_ID}\" \/>" ${SERVER_CONFIG};
            else
                sed -i "/<\/Membership>/i \<Member className=\"org.apache.catalina.tribes.membership.StaticMember\" port=\"4004\" host=\"${1}\" uniqueId=\"{0,1,2,3,4,5,6,7,8,9,10,$MEMBER_ID}\" \/>" ${SERVER_CONFIG};
            fi
        fi
    else
        [[ "x${CURRENT_NODE_INTERNAL_IP}" == "x${1}" ]] && return 0;
        grep -q "Member.*host=\"${1}\"" ${SERVER_CONFIG} || \
            sed -i "/org.apache.catalina.tribes.group.interceptors.StaticMembershipInterceptor/a \<Member className=\"org.apache.catalina.tribes.membership.StaticMember\" port=\"4004\" host=\"${1}\" uniqueId=\"{0,1,2,3,4,5,6,7,8,9,10,$MEMBER_ID}\" \/>" ${SERVER_CONFIG};
    fi
}

cleanupNodes(){
    sed -i "/Member.*host=.*uniqueId=.*/d" ${SERVER_CONFIG};
}

applyHostIpInConfig(){
    sed -i "s/defaultHost=\"localhost\"/defaultHost=\"${CURRENT_NODE_INTERNAL_IP}\"/g" ${SERVER_CONFIG}; 
    sed -i "s/Host[[:space:]]*name=\"localhost\"/Host name=\"${CURRENT_NODE_INTERNAL_IP}\"/g" ${SERVER_CONFIG};
    sed -i "s/Receiver[[:space:]]*address=\"[0-9\.]*\"/Receiver address=\"${CURRENT_NODE_INTERNAL_IP}\"/g" ${SERVER_CONFIG};
}

addConfigToRedeployConf(){
    grep -q ${SERVER_CONFIG} "${REDEPLOY_CONF}" || echo "${SERVER_CONFIG}" >> "${REDEPLOY_CONF}";
}

removeClusterConfig(){
    xmlstarlet ${ED_CMD} -d ${CLUSTER_XPATH} ${SERVER_CONFIG};
}

checkClusterConfig(){
    if [ $# -eq 0 ]
    then
        echo "No arguments supplied";
        return 1;
    fi
    grep -q "StaticMembershipService" ${SERVER_CONFIG} && NEW_CONFIG="true" || NEW_CONFIG="false"
    if [ "$NEW_MANIFEST" == "$NEW_CONFIG" ]; then
        return 0;
    else
        cp -f ${SERVER_CONFIG} ${SERVER_CONFIG}.backup
        if [ "$NEW_MANIFEST" == "true" ]; then
            xmlstarlet ${ED_CMD} -d "Server/Listener[@className='org.apache.catalina.core.JasperListener']" ${SERVER_CONFIG};
        fi
        xmlstarlet ${ED_CMD} -d "${CLUSTER_XPATH}/Channel/Interceptor[@className='org.apache.catalina.tribes.group.interceptors.StaticMembershipInterceptor']" ${SERVER_CONFIG};
        xmlstarlet ${ED_CMD} -d "${CLUSTER_XPATH}/Channel/Interceptor[@className='org.apache.catalina.tribes.group.interceptors.TcpPingInterceptor']" ${SERVER_CONFIG};
        xmlstarlet ${ED_CMD} -d "${CLUSTER_XPATH}/Channel/Receiver[@className='org.apache.catalina.tribes.transport.nio.NioReceiver']" ${SERVER_CONFIG};
        xmlstarlet ${ED_CMD} -d "${CLUSTER_XPATH}/Channel/Membership" ${SERVER_CONFIG};
        xmlstarlet ${ED_CMD} -d "${CLUSTER_XPATH}/Channel/Interceptor[@className='org.apache.catalina.tribes.group.interceptors.ThroughputInterceptor']" ${SERVER_CONFIG};
        addVersionSpecificConfig ${1}
    fi
}

case ${1} in 
   applyClusterTemplate)
       applyClusterTemplate "${2}"
       ;;
   addNode)
       addNode "${2}" "${3}"
       ;;        
   removeNode) 
       removeNode "${2}" 
       ;; 
   cleanupNodes)
       cleanupNodes
       ;;
   applyHostIpInConfig)
       applyHostIpInConfig
       ;;
   addConfigToRedeployConf)
       addConfigToRedeployConf
       ;;
   removeClusterConfig)
       removeClusterConfig
       ;;
   checkClusterConfig)
       checkClusterConfig ${2}
       ;;
esac
