#!/bin/bash 

XMLSTARLET=$(which xmlstarlet) 
ED_CMD="ed --inplace"
SERVER_CONFIG="/opt/tomcat/conf/server.xml"
REDEPLOY_CONF="/etc/jelastic/redeploy.conf"
CURRENT_NODE_INTERNAL_IP=$(ip a | grep -A1 venet0 | grep inet | awk '{print $2}'| sed 's/\/[0-9]*//g' | tail -n 1)
[ -f /etc/jelastic/metainf.conf ] && . /etc/jelastic/metainf.conf 

[ -f /etc/jelastic/metainf.conf ] && source /etc/jelastic/metainf.conf

if [[ "x$COMPUTE_TYPE" == "xtomee" ]]; then
   NEW_MANIFEST="true";
elif [[ $COMPUTE_TYPE_VERSION -le 8 ]]; then
   NEW_MANIFEST="false";
else
   NEW_MANIFEST="true";
fi

applyClusterTemplate(){
    if [ "$NEW_MANIFEST" == "true" ]; then
        sed -i "/<\/Host>/e curl ${1}/conf/cluster.tpl" ${SERVER_CONFIG};
    else
        sed -i "/<\/Host>/e curl ${1}/conf/cluster-old.tpl" ${SERVER_CONFIG};
    fi
}

removeNode(){
    if [ "$NEW_MANIFEST" == "true" ]; then
        [[ "x${CURRENT_NODE_INTERNAL_IP}" == "x${1}" ]] && return 0;
    fi
    sed -i "/Member.*host=${1}/d" ${SERVER_CONFIG};
}

addNode(){
    MEMBER_ID=$(echo ${1} | sed 's/\./,/g'); 
    if [ "$NEW_MANIFEST" == "true" ]; then
        grep -q "Member.*host=\"${1}\"" ${SERVER_CONFIG} || \
            sed -i "/<\/Membership>/i \<Member className=\"org.apache.catalina.tribes.membership.StaticMember\" port=\"4004\" host=\"${1}\" uniqueId=\"{0,1,2,3,4,5,6,7,8,9,10,11,$MEMBER_ID}\" \/>" ${SERVER_CONFIG};
    else
        [[ "x${CURRENT_NODE_INTERNAL_IP}" == "x${1}" ]] && return 0;
        grep -q "Member.*host=\"${1}\"" ${SERVER_CONFIG} || \
            sed -i "/org.apache.catalina.tribes.group.interceptors.StaticMembershipInterceptor/a \<Member className=\"org.apache.catalina.tribes.membership.StaticMember\" port=\"4004\" host=\"${1}\" uniqueId=\"{0,1,2,3,4,5,6,7,8,9,10,11,$MEMBER_ID}\" \/>" ${SERVER_CONFIG};
    fi
}

cleanupNodes(){
    sed -i "/Member.*host=.*uniqueId=.*/d" ${SERVER_CONFIG};
}

applyHostIpInConfig(){
    sed -i "s/defaultHost=\"localhost\"/defaultHost=\"${CURRENT_NODE_INTERNAL_IP}\"/g" ${SERVER_CONFIG}; 
    sed -i "s/Host[[:space:]]*name=\"localhost\"/Host name=\"${CURRENT_NODE_INTERNAL_IP}\"/g" ${SERVER_CONFIG};
    sed -i "s/Receiver[[:space:]]*address=\"[0-9\.]*\"/Receiver address=\"${CURRENT_NODE_INTERNAL_IP}\"/g" ${SERVER_CONFIG};
}

addConfigToRedeployConf(){
    grep -q ${SERVER_CONFIG} "${REDEPLOY_CONF}" || echo "${SERVER_CONFIG}" >> "${REDEPLOY_CONF}";
}

removeClusterConfig(){
    xmlstarlet ed --inplace -P -d Server/Service/Engine/Host/Cluster ${SERVER_CONFIG};
}

case ${1} in 
   applyClusterTemplate)
       applyClusterTemplate "${2}"
       ;;
   addNode)
       addNode "${2}" 
       ;;        
   removeNode) 
       removeNode "${2}" 
       ;; 
   cleanupNodes)
       cleanupNodes
       ;;
   applyHostIpInConfig)
       applyHostIpInConfig
       ;;
   addConfigToRedeployConf)
       addConfigToRedeployConf
       ;;
   removeClusterConfig)
       removeClusterConfig "${2}"
       ;;
esac
